# Site settings
site_title: My Haskell Blog
email: your-email@domain.com
description:  Write an awesome description for your new site here. You can edit this line in config.yml.
baseurl: ""
twitter: hakyllhs
github:  hakyll
